package dao;

import model.Diary;
import model.DiaryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DiaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbg.generated
     */
    long countByExample(DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbg.generated
     */
    int deleteByExample(DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer diaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbg.generated
     */
    int insert(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbg.generated
     */
    int insertSelective(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbg.generated
     */
    List<Diary> selectByExample(DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbg.generated
     */
    Diary selectByPrimaryKey(Integer diaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Diary record, @Param("example") DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Diary record, @Param("example") DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Diary record);
}