package model;

public class Diary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.diary_id
     *
     * @mbg.generated
     */
    private Integer diaryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.diary_comment
     *
     * @mbg.generated
     */
    private String diaryComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.diary_content
     *
     * @mbg.generated
     */
    private String diaryContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.diary_id
     *
     * @return the value of diary.diary_id
     *
     * @mbg.generated
     */
    public Integer getDiaryId() {
        return diaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.diary_id
     *
     * @param diaryId the value for diary.diary_id
     *
     * @mbg.generated
     */
    public void setDiaryId(Integer diaryId) {
        this.diaryId = diaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.diary_comment
     *
     * @return the value of diary.diary_comment
     *
     * @mbg.generated
     */
    public String getDiaryComment() {
        return diaryComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.diary_comment
     *
     * @param diaryComment the value for diary.diary_comment
     *
     * @mbg.generated
     */
    public void setDiaryComment(String diaryComment) {
        this.diaryComment = diaryComment == null ? null : diaryComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.diary_content
     *
     * @return the value of diary.diary_content
     *
     * @mbg.generated
     */
    public String getDiaryContent() {
        return diaryContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.diary_content
     *
     * @param diaryContent the value for diary.diary_content
     *
     * @mbg.generated
     */
    public void setDiaryContent(String diaryContent) {
        this.diaryContent = diaryContent == null ? null : diaryContent.trim();
    }
}